# Generated by Django 3.0.2 on 2020-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0002_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(),
        ),
    ]
