# Generated by Django 3.0.2 on 2020-08-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0008_auto_20200809_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
