# Generated by Django 3.0.2 on 2020-08-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0009_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddField(
            model_name='todo',
            name='daily_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
