# Generated by Django 3.0.2 on 2020-08-16 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0010_auto_20200816_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 15, 35, 48, 767914)),
        ),
    ]
