# Generated by Django 3.0.2 on 2020-08-17 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0011_todo_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='daily_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='reminder_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 20, 8, 21, 749992)),
        ),
    ]
