# Generated by Django 3.0.2 on 2020-08-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0014_auto_20200817_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_items.Todo')),
            ],
        ),
    ]
