# Generated by Django 3.0.2 on 2020-08-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0017_auto_20200822_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_items.Todo_Group'),
        ),
        migrations.DeleteModel(
            name='Todo_Groups',
        ),
    ]
