# Generated by Django 3.0.2 on 2020-08-27 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0020_auto_20200823_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='custom_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='reminder_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
