# Generated by Django 3.0.2 on 2020-08-29 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('todo_items', '0021_auto_20200828_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabSchedule',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.CrontabSchedule')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 13, 13, 18, 191530)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='reminder_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 29, 13, 13, 18, 191530)),
        ),
    ]
