# Generated by Django 3.0.2 on 2020-08-29 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_items', '0022_auto_20200829_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 14, 13, 6, 4536)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='reminder_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 29, 14, 13, 6, 5537)),
        ),
    ]
